---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-go
spec:
  template:
    spec:
      containers:
        - name: go
          image: go
          imagePullPolicy: IfNotPresent
          ports:
            - name: go
              containerPort: 80
          livenessProbe:
            tcpSocket:
              port: go
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: go
            initialDelaySeconds: 10
            timeoutSeconds: 5
