---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01
spec:
  template:
    spec:
      containers:
        - name: amqproxy
          image: teamleader/amqproxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqproxy
              containerPort: 5673
          livenessProbe:
            tcpSocket:
              port: amqproxy
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: amqproxy
            initialDelaySeconds: 5
            timeoutSeconds: 5
