---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-worker
spec:
  template:
    spec:
      containers:
        - name: worker-twemproxy
          image: worker-twemproxy
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-twemproxy-config
              mountPath: "/opt"
          args:
            - "/usr/sbin/nutcracker"
            - "-c"
            - "/opt/nutcracker.yml"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          livenessProbe:
            tcpSocket:
              port: 22222
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 22222
            initialDelaySeconds: 15
            periodSeconds: 20
