---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  template:
    spec:
      containers:
        - name: nodejs
          image: nodejs
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: cm
                  key: environment
          ports:
            - name: node
              containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health_check
              port: node
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health_check
              port: node
            initialDelaySeconds: 10
            timeoutSeconds: 5
