---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "/usr/local/bin/entrypoint.sh"]
          env:
            - name: NODE_DNS
              value: "127.0.0.1"
            - name: PHP_DNS
              value: "127.0.0.1"
          ports:
            - name: nginx
              containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          livenessProbe:
            tcpSocket:
              port: nginx
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: nginx
            initialDelaySeconds: 5
            timeoutSeconds: 5
