---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-worker
spec:
  template:
    spec:
      containers:
        - name: worker-php
          image: worker-php
          imagePullPolicy: IfNotPresent
