---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-node
spec:
  template:
    spec:
      containers:
        - name: node
          image: node
          imagePullPolicy: IfNotPresent
          ports:
            - name: node
              containerPort: 3001
          livenessProbe:
            tcpSocket:
              port: node
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: node
            initialDelaySeconds: 5
            timeoutSeconds: 5
