name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  release:
    if: github.event_name != 'pull_request'
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ steps.get_workflow_token.outputs.token }}
          prerelease: false
